# These are supported funding model platforms

github: [proudmonkey]
patreon: # Replace with a single Patreon username
tidelift: # nuget/AutoWrapper.Core
custom: ["https://www.paypal.me/vmsdurano", "https://www.buymeacoffee.com/ImP9gONBW"]
